"""Central configuration. Every path and resource knob can be set with an environment variable.

run_all.py sets these from its command-line arguments, so you normally do not edit this file.

  BER_DATA     folder containing train/ and test/ with the original .tsv files
               (e.g. .../student_resource/dataset)
  BER_WORK     scratch folder for intermediate files (needs ~40 GB free disk)
  BER_OUT      where matching_results.tsv and candidate_pairs.tsv are written
  BER_ART      where trained models / dictionaries are stored (default: <BER_WORK>/artifacts)
  BER_THREADS  CPU threads for LightGBM / multiprocessing (default: all cores)
  BER_MEM_GB   RAM available; >= 24 switches to larger, faster chunks (default: 6)
"""
import os

DATA = os.environ.get("BER_DATA", "dataset")
WORK = os.environ.get("BER_WORK", "work")
OUT = os.environ.get("BER_OUT", "output")
ART = os.environ.get("BER_ART", os.path.join(WORK, "artifacts"))
THREADS = int(os.environ.get("BER_THREADS", os.cpu_count() or 2))
MEM_GB = float(os.environ.get("BER_MEM_GB", "6"))
BIG = MEM_GB >= 24

# chunking (small values keep peak memory under ~5 GB; big machines use fewer, larger chunks)
BLOCK_S1_CHUNK = 20000 if BIG else 5000
PRUNE_CHUNKS = 6 if BIG else 24
FEAT_CHUNKS = 5 if BIG else 20
PREP_BLOCK = 1_000_000 if BIG else 400_000

DICT_PATH = os.path.join(ART, "indic_dict.json")
XGB = os.environ.get("BER_XGB", "0") == "1"      # add XGBoost to stage 1 (ensemble with LightGBM)

for _d in (WORK, ART, OUT):
    os.makedirs(_d, exist_ok=True)
